### PR TITLE
Wip/baratinoo

### PR DESCRIPTION
**Pull request by rpoitevin**
Module supporting Voxygen, a proprietary TTS.
https://voxygen.fr/

### CODE REVIEW

**Comment by TheMuso** [comment]
I see that there are English Voxygen voices, and they appear to have an English site too, http://voxygen-group.com. I am wondering whether I need to apply to get access to the SDK, or whether the SDK files come with a particular version of the product. If the latter, which product do I need to get so I can test and build this driver locally?

**Comment by rpoitevin** [comment]
Hi Luke,

On 04/19/2017 04:26 AM, Luke Yelavich wrote:
> I see that there are English Voxygen voices, and they appear to have an
> English site too, http://voxygen-group.com. I am wondering whether I
> need to apply to get access to the SDK, or whether the SDK files come
> with a particular version of the product. If the latter, which product
> do I need to get so I can test and build this driver locally?

To get the SDK we had to contract with the company. We could get because 
our aim is to integrate their product in our system and resell it.

Maybe can you contact them. I know there interested in studying 
speech-dispatcher to understand how does it work.

I will ask them how does it work with the none SDK version.

Regards,

Raphaël

**Comment by TheMuso** [comment]
On Thu, Apr 20, 2017 at 07:41:44PM AEST, rpoitevin wrote:
> Maybe can you contact them. I know there interested in studying 
> speech-dispatcher to understand how does it work.

Certainly worth pursuing, thanks.

> I will ask them how does it work with the none SDK version.

Thanks. Eventually, it will be possible for drivers to be buildable and maintainable out of tree, but a lot needs doing before we get there, which is why I try and get a hold of synths, such that I can test them when bigger changes are made accross the project.

Luke

**Comment by rpoitevin** [comment]
Hi Luke,

With our contract, we are authorized to get activations running until 
Apr 30th.

I invite you to install the SDK. I wrote a procedure in attachement.

You can folow the two first steps and send me the generated file in 2.2. 
I will ask an activation for you.

Regards,

Raphaël

On 04/20/2017 12:14 PM, Luke Yelavich wrote:
> On Thu, Apr 20, 2017 at 07:41:44PM AEST, rpoitevin wrote:
>> Maybe can you contact them. I know there interested in studying
>> speech-dispatcher to understand how does it work.
>
> Certainly worth pursuing, thanks.
>
>> I will ask them how does it work with the none SDK version.
>
> Thanks. Eventually, it will be possible for drivers to be buildable and
> maintainable out of tree, but a lot needs doing before we get there,
> which is why I try and get a hold of synths, such that I can test them
> when bigger changes are made accross the project.
>
> Luke

Install Voxygen (baratinoo module)

This howto is based on the SDK version. It supposed to be modified
according to the standard version.

1. Download the archive:
https://owncloud.hypra.fr/index.php/s/Y2Y7RgIulXb39w6
1.1. cd /opt
1.2. tar -xzf Voxygen_TTS_SDK_C_linux_7.6_2.tgz

2. Generate an activation code:
2.1. cd /opt/Voxygen_TTS_SDK_C_linux_7.6_2/bin/linx64
2.2. ./lic_id
2.3. Send me the generated file baratinoo.uid
The activation will run until Apr 30th.
2.4. Put the delivered file into /opt/Voxygen_TTS_SDK_C_linux_7.6_2/config/

3. unzip voices:
3.1. Download voices here (Paul for english):
https://depot.voxygen.fr/jpmengual@hypra.fr
Login : jpmengual@hypra.fr
Password : 37nqblWFxZ
3.2. cd /opt/Voxygen_TTS_SDK_C_linux_7.6_2/config
3.3. tar -xzf <voice_file>

4. To test, compile the demonstration programme:
4.1. cd /opt/Voxygen_TTS_SDK_C_linux_7.6_2/c_api/barademo_C/linx64
4.2. make
4.3. cd /opt/Voxygen_TTS_SDK_C_linux_7.6_2/bin/linx64
export LD_LIBRARY_PATH=$PWD
4.5. ./barademo_C
4.6. aplay barademo_C.wav

5. Declare baratinoo library path:
5.1. sudo vi /etc/ld.so.conf/baratinoo.conf
/opt/Voxygen_TTS_SDK_C_linux_7.6_2/bin/linx64
5.2. sudo ldconfig
5.3. sudo vi /etc/speech-dispatcher/modules/baratinoo.conf
5.4. change this line:
#BaratinooConfigPath    "/opt/voxygen/config/baratinoo.cfg"
into:
BaratinooConfigPath	"/opt/Voxygen_TTS_SDK_C_linux_7.6_2/config/baratinoo.cfg"

**Comment by sthibaul** [comment]
@TheMuso I can review the branch if that helps. AIUI you are fine with appending Reviewed-by tags within the history itself? (thus forcing updates for others)

**Comment by sthibaul** [comment]
I see that this is still a development branch with fixes over fixes etc. Perhaps we should just squash it altogether in just one commit which adds the resulting file? (possibly with adding comments as to why some of the lines were changed)

**Comment by rpoitevin** [comment]
Closing this pull request to open a new one in order to squash all commits in a signle one.

**Pull request closed without merging**
