### PR TITLE
Wip/preprocessed punctuation

### PR DESCRIPTION
**Pull request by rpoitevin**
Manage punctuation processing.

### CODE REVIEW

**Comment by TheMuso** [comment]
Are the NVDA symbols files under GPL 2? I see the mention of the GPL in their headers, but nothing about the version.

As for the list building, maybe the GQueue data structure from GLib is worth considering. It keeps a pointer to the first and last element of the list, and whilst it uses double linked lists, one can append entries to a GQueue managed list, and not have to walk the list every time. In addition, the list would not even need to be reversed, so no list walking would ever be needed.

Another option could be to locally implement similar functionality to what the GQueue API provides, but using a single linked list. Have a pointer to the start of the list, and have a variable that always points to the end, for easy adding of items, such that the list only ever needs to be walked when the data is being processed.

I will take a closer look at the list code, and may do that myself, but thoughts or other suggestions are welcome.

**Comment by cwendling** [comment]
> Are the NVDA symbols files under GPL 2? I see the mention of the GPL in their headers, but nothing about the version.

Yes, AFAIK they are, or at the very least it seems to be the intention the developers had, given some initial discussion on IRC.  See also their [copying.txt](https://github.com/nvaccess/nvda/blob/master/copying.txt).

> As for the list building, maybe the GQueue data structure from GLib is worth considering. […]

GQueue has a space overhead that might be more noticeable than the computing one (especially with the reversion which traverses the list only once, only moving pointers), as most of it is only done once anyway, but the result is cached.
Anyway, I'm not really convinced this is worth spending too much time over unless it shows up in a profiler.  I don't have numbers, but walking over the code quickly suggested there probably are other places more likely to be easily optimized, if the need ever arises.  IMO in this particular case, merely appending to the list walking it every time *might* have a somewhat noticeable impact, but readability and maintainability are more important here if a choice has to be made.

So in the end I'd say you should keep what you prefer.  And not implement a new container, because it's not worth the hassle.

**Comment by alexarnaud** [comment]
Hello @TheMuso ,

Is the pull request OK? Do we need to do something to make it integrated into speech-dispatcher?

Best regards.

**Comment by sthibaul** [comment]
Hello @TheMuso , I see that reviewing happened, is there some work left to do on this? I can help with it.

**Pull request closed without merging**
