### PR TITLE
Wip/kali

### PR DESCRIPTION
**Pull request by rpoitevin**

### CODE REVIEW

**Comment by rpoitevin** [comment]
Hi Luke,

Thank you for merging!

What are the steps now to be integrated officially?

Regards,

Raphaël

**Comment by sthibaul** [comment]
@TheMuso I can also help with this one. It seems you did some integration changes, but AIUI you haven't yet had the opportunity to review the code?

**Comment by alexarnaud** [comment]
@TheMuso What's happened with this PR ? It's mark as closed but I don't see any merge into speech-dispatcher tree. Are you waiting for changes from Hypra ?

Best regards.

**Comment by alexarnaud** [comment]
@sthibaul Do you want a new pull request on the new speech-dispatcher repository with a single commit ?

Best regards.

**Comment by sthibaul** [comment]
I created https://github.com/brailcom/speechd/pull/5 from the wip/kali branch, I'll review it.

**Pull request merged**
