### PR TITLE
use wave buffer instead wave file

### PR DESCRIPTION
**Pull request by rpoitevin**

### CODE REVIEW

**Comment by TheMuso** [comment]
I tried to build this, but it seems there is no definition of AudioTrackKali anywhere. I downloaded the trial version again to see if that was updated, but it doesn't seem to be. Is there anywhere I can get the updated headers and libraries?

Thanks.

**Comment by rpoitevin** [comment]
Hi Luke.

On 12/14/2016 09:40 PM, Luke Yelavich wrote:
> I tried to build this, but it seems there is no definition of
> AudioTrackKali anywhere. I downloaded the trial version again to see if
> that was updated, but it doesn't seem to be. Is there anywhere I can get
> the updated headers and libraries?

Sorry. I didn't have the time to give you more precision by email. Just 
wait a moment please, I'll build a new package of Kali.

Regards,

Raphaël

**Comment by rpoitevin** [comment]
Hi Luke,

Here a new version of Kali:
https://owncloud.hypra.fr/index.php/s/wK8SdWISwJ3sZJk/download

We've renamed kali into kali-tts because we noticed there was an other 
package named kali in Debian which has no relation with our project. I 
don't remember if the package I gave you was kali or kali-tts.

Regards,

**Comment by TheMuso** [comment]
On Fri, Dec 16, 2016 at 01:44:11AM AEDT, rpoitevin wrote:
> Hi Luke,
> 
> Here a new version of Kali:
> https://owncloud.hypra.fr/index.php/s/wK8SdWISwJ3sZJk/download

Thanks, but this doesn't appear to have any header files in it...

Luke

**Comment by rpoitevin** [comment]
Hi Luke,

On 12/28/2016 10:10 AM, Luke Yelavich wrote:
> Thanks, but this doesn't appear to have any header files in it...

Sorry again! Here is the kali.h. I don't remember if I sent you the 
first time an archive with the complete tree or a deb package. If you 
have the complete tree, this file should be placed in Kali subdirectory. 
But maybe did you put all files in your own include.

Regards,

Raphaël

**Pull request closed without merging**
